### ISSUE TITLE
RuntimeError: Maximum device count of 10 exceeded.

### ISSUE THREAD

**Issue by robmarkcole** [adafruit/Adafruit_CircuitPython_OneWire#16]
Attempting to use the DS18X20 with Metro M4 Airlift Lite with circuitpython 5.0.0-beta.0 I get the following error:

```
ds18 = DS18X20(ow_bus, ow_bus.scan()[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_onewire/bus.py", line 156, in scan
RuntimeError: Maximum device count of 10 exceeded.
```

**Comment by tannewt** [comment]
This is intentional. Here is the discussion for adding it: https://github.com/adafruit/Adafruit_CircuitPython_OneWire/issues/7

You can set maximum_devices on the bus object higher to not hit this limit. https://github.com/adafruit/Adafruit_CircuitPython_OneWire/blob/master/adafruit_onewire/bus.py#L90
